apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    service: grafana
spec:
  type: NodePort
  selector:
    run: grafana
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      run: grafana
  template:
    metadata:
      labels:
        run: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          env:
            - name: GF_INSTALL_PLUGINS
              value: grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
